apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # Allow the volume to be mounted as read-write by a single node
  resources:
    requests:
      storage: 2Gi # Request 2 gigabytes of storage